language: java

addons:
  sonarcloud:
    organization: "1809-spark-usf"
    
jobs:
  include:
    - stage: test
      script: mvn test
    
    - stage: build-quality
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
